=== camilo1822/trabajoCasa/SHP.CMM.ServiceInterface/main/resources/SHP_MSG_ESB.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema targetNamespace="http://www.grupobancolombia.com/BandaDigital/services/SHP_MSG_ESB" elementFormDefault="qualified" xmlns="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.grupobancolombia.com/BandaDigital/services/SHP_MSG_ESB">

    <element name="requestHeaderOut" type="tns:requestHeaderOutType"></element>

    <complexType name="requestHeaderOutType">
    	<sequence>
    		<element name="Header" type="tns:HeaderRequestType"></element>
    		<element name="Body" type="tns:BodyType"></element>
    	</sequence>
    </complexType>

    <complexType name="HeaderRequestType">
    	<sequence>
    		<element name="systemId" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="messageId" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="invokerDateTime" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="securityCredential"
    			type="tns:securityCredentialType" minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="destination" type="tns:destinationType"
    			minOccurs="1" maxOccurs="1">
    		</element>
    		<element name="messageContext" type="tns:MessageContextType" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="securityCredentialType">
    	<sequence>
    		<element name="userName" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="userToken" type="string" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="destinationType">
    	<sequence>
    		<element name="name" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="namespace" type="string" minOccurs="1"
    			maxOccurs="1">
    		</element>
    		<element name="operation" type="string" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>

    <complexType name="BodyType">
    	<sequence>
    		<any minOccurs="0"/>
    	</sequence>
    </complexType>

    <element name="responseHeaderOut" type="tns:responseHeaderOutType"></element>

    <complexType name="responseHeaderOutType">
    	<sequence>
    		<element name="Header" type="tns:HeaderResponseType"></element>
    		<element name="Body" type="tns:BodyType"></element>
    	</sequence>
    </complexType>

    <complexType name="HeaderResponseType">
    	<sequence>
    		<element name="systemId" type="string"></element>
    		<element name="messageId" type="string"></element>
    		<element name="invokerDateTime" type="string"></element>
            <element name="destination" type="tns:destinationType"></element>
            <element name="responseStatus"
    			type="tns:ResponseStatusType">
    		</element>
    	</sequence>
    </complexType>

    <complexType name="ResponseStatusType">
    	<sequence>
    		<element name="statusDesc" type="string"></element>
    		<element name="statusCode" type="string"></element>
    		<element name="errorMessage" type="string"></element>
    		<element name="system" type="string"></element>
    	</sequence>
    </complexType>

    <element name="RequestHeaderOutMessage" type="tns:RequestHeaderOutMessageType"></element>

    <complexType name="RequestHeaderOutMessageType">
    	<sequence>
    		<element name="requestHeaderOut" type="tns:requestHeaderOutType"></element>
    	</sequence>
    </complexType>

    <element name="responseHeaderOutMessage" type="tns:responseHeaderOutMessageType"></element>

    <complexType name="responseHeaderOutMessageType">
    	<sequence>
    		<element name="responseHeaderOut" type="tns:responseHeaderOutType"></element>
    	</sequence>
    </complexType>

    <complexType name="MessageContextType">
    	<sequence>
    		<element name="property" type="tns:PropertyType" minOccurs="0" maxOccurs="unbounded"></element>
    	</sequence>
    </complexType>

    <complexType name="PropertyType">
    	<sequence>
    		<element name="key" type="string" minOccurs="1" maxOccurs="1"></element>
    		<element name="value" type="string" minOccurs="1" maxOccurs="1"></element>
    	</sequence>
    </complexType>
</schema>

=== camilo1822/trabajoCasa/SHP.ADM.MessageLibrary/src/main/resources/samples/SHP_MSG_ESB_Request.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:RequestHeaderOutMessage xmlns:tns="http://www.grupobancolombia.com/BandaDigital/services/SHP_MSG_ESB" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.grupobancolombia.com/BandaDigital/services/SHP_MSG_ESB ../resources/SHP_MSG_ESB.xsd ">
  <tns:requestHeaderOut>
    <tns:Header>
      <tns:systemId>tns:systemId</tns:systemId>
      <tns:messageId>tns:messageId</tns:messageId>
      <tns:invokerDateTime>tns:invokerDateTime</tns:invokerDateTime>
      <tns:securityCredential>
        <tns:userName>tns:userName</tns:userName>
        <tns:userToken>tns:userToken</tns:userToken>
      </tns:securityCredential>	
      <tns:destination>
        <tns:name>tns:name</tns:name>
        <tns:namespace>tns:namespace</tns:namespace>
        <tns:operation>tns:operation</tns:operation>
      </tns:destination>
      <tns:messageContext>
      	<tns:property>
      		<tns:key></tns:key>
      		<tns:value></tns:value>
      	</tns:property>
      	<tns:property>
      		<tns:key></tns:key>
      		<tns:value></tns:value>
      	</tns:property>
      </tns:messageContext>
    </tns:Header>
    <tns:Body/>
  </tns:requestHeaderOut>
</tns:RequestHeaderOutMessage>

=== camilo1822/trabajoCasa/SHP.ADM.MessageLibrary/src/main/resources/samples/SHP_MSG_ESB_REsponse.xml
<?xml version="1.0" encoding="UTF-8"?>
<responseHeaderOutMessage xmlns="http://www.grupobancolombia.com/BandaDigital/services/SHP_MSG_ESB" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.grupobancolombia.com/BandaDigital/services/SHP_MSG_ESB ../resources/SHP_MSG_ESB.xsd ">
  <responseHeaderOut>
    <Header>
      <systemId>systemId</systemId>
      <messageId>messageId</messageId>
      <invokerDateTime>invokerDateTime</invokerDateTime>
      
      <destination>
        <name>name</name>
        <namespace>namespace</namespace>
        <operation>operation</operation>
      </destination>
      <responseStatus>
        <statusDesc>statusDesc</statusDesc>
        <statusCode>statusCode</statusCode>
        <errorMessage></errorMessage>
        <system></system>
        
      </responseStatus>
    </Header>
    <Body/>
  </responseHeaderOut>
</responseHeaderOutMessage>

=== camilo1822/trabajoCasa/SHP.ADM.MessageLibrary/src/main/resources/samples/SHP_MSG_ESB.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:responseHeaderOutMessage xmlns:tns="http://www.grupobancolombia.com/BandaDigital/services/SHP_MSG_ESB" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.grupobancolombia.com/BandaDigital/services/SHP_MSG_ESB ../resources/SHP_MSG_ESB.xsd ">
  <tns:responseHeaderOut>
    <tns:Header>
      <tns:systemId>tns:systemId</tns:systemId>
      <tns:messageId>tns:messageId</tns:messageId>
      <tns:invokerDateTime>tns:invokerDateTime</tns:invokerDateTime>
      
      <tns:destination>
        <tns:name>tns:name</tns:name>
        <tns:namespace>tns:namespace</tns:namespace>
        <tns:operation>tns:operation</tns:operation>
      </tns:destination>
      <tns:responseStatus>
        <tns:statusDesc>tns:statusDesc</tns:statusDesc>
        <tns:statusCode>tns:statusCode</tns:statusCode>
        
        <tns:errorMessage></tns:errorMessage>
        <tns:system></tns:system>
      </tns:responseStatus>
    </tns:Header>
    <tns:Body/>
  </tns:responseHeaderOut>
</tns:responseHeaderOutMessage>
